import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1685476588592 implements MigrationInterface {
    name = 'Init1685476588592'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "data_paises" ("id" SERIAL NOT NULL, "codigo" character varying(50), "nombre" character varying(250) NOT NULL, "descripcion" character varying(250), "active" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91bd8ea2dccdb82da59a0c730b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "persona_natural" ("id" SERIAL NOT NULL, "tipo_identificacion" character varying(50), "nro_identificacion" character varying(50), "nombres" character varying(50), "primer_apellido" character varying(50), "segundo_apellido" character varying(50), "apellido_casada" character varying(50), "fecha_nacimiento" TIMESTAMP, "genero" character varying(10) DEFAULT 'hombre', "email" character varying(100), "telefono" character varying(10), "direccion" character varying(250), "profesion" character varying(50) DEFAULT 'estudiante', "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_pais" integer, CONSTRAINT "PK_e1782b2b53eb1d0ada12bb15529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categoria_registro" ("id" SERIAL NOT NULL, "nivel" integer NOT NULL DEFAULT '1', "categoria" character varying(50) NOT NULL, "codigo" character varying(50), "descripcion" character varying(250), "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_9ce21c2f082ec2dc1c7fa21827e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "data_estados_departamentos" ("id" SERIAL NOT NULL, "codigo" character varying(50), "nombre" character varying(250) NOT NULL, "descripcion" character varying(250), "active" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "id_pais" integer, CONSTRAINT "PK_a29ff17c357561d1c2bad263419" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "data_ciudades_municipios" ("id" SERIAL NOT NULL, "codigo" character varying(50), "nombre" character varying(250) NOT NULL, "descripcion" character varying(250), "active" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "id_estado_departamento" integer, CONSTRAINT "PK_b5203ea9c1cce08a6a02fb9d42a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalogo" ("id" SERIAL NOT NULL, "nivel" integer NOT NULL DEFAULT '1', "categoria" character varying(50) NOT NULL, "codigo" character varying(50), "descripcion" character varying(250), "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_b545f16d7a23efa494bb2dd5994" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categoria_empresa" ("id" integer NOT NULL, "nivel" integer NOT NULL DEFAULT '1', "categoria" character varying(50) NOT NULL, "codigo" character varying(50), "descripcion" character varying(250), "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_c30858b2e250bb009b3d487ab66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "empresas" ("id" SERIAL NOT NULL, "codigo" character varying(50) NOT NULL, "sigla" character varying(50), "nombre" character varying(250), "nombre_corto" character varying(250), "nro_seprem" character varying(50), "nit" character varying(50), "email" character varying(250), "telefono" character varying(250), "direccion" character varying(250), "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_tipo_empresa" integer, CONSTRAINT "PK_ce7b122b37c6499bfd6520873e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "registros_hechos_posteriores" ("id" SERIAL NOT NULL, "fecha_registro" TIMESTAMP, "descripcion" text, "estado" character varying(50) NOT NULL, "observaciones" text, "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_registros_baja" integer, "id_categoria_hechos_posteriores" integer, CONSTRAINT "PK_23ebcba04aaffcf285ad61b1537" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "registros_bajas" ("id" SERIAL NOT NULL, "nro_baja" character varying(50) NOT NULL, "fecha_baja" TIMESTAMP, "comentarios" text, "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_registro_funcionario" integer, "id_categoria_baja" integer, CONSTRAINT "PK_e19c5b356e6461881ced7378f62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "registros_funcionarios" ("id" SERIAL NOT NULL, "tipo_directivo" character varying(50), "tipo_funcionario" character varying(50), "tipo_contrato" character varying(50), "estado" character varying(50) NOT NULL DEFAULT 'activo', "nro_contrato" character varying(50), "tipo_apoderado" character varying(50), "cargo" character varying(50) NOT NULL, "fecha_ingreso" TIMESTAMP, "codigo_colegiatura" character varying(50), "nro_representacion_legal" character varying(50), "fecha_inicio_representacion_legal" TIMESTAMP, "fecha_fin_representacion_legal" TIMESTAMP, "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_persona" integer, "id_empresa" integer, "id_tipo_cargo" integer, "id_estado_departamento" integer, "id_ciudad_municipio" integer, CONSTRAINT "PK_73d3fd87b1e4d08a4ae295086e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "solicitudes" ("id" SERIAL NOT NULL, "tipo_solicitud" character varying(50), "descripcion" character varying(500), "respuesta" character varying(500), "estado" character varying(50), "usuario_solicitud" character varying(50), "fecha_solicitud" TIMESTAMP, "usuario_aprobacion" character varying(50), "fecha_aprobacion" TIMESTAMP, "status" boolean NOT NULL DEFAULT true, "usuario_creacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "usuario_modificacion" character varying(50) NOT NULL DEFAULT 'default', "fecha_modificacion" TIMESTAMP DEFAULT now(), "id_empresa" integer, "id_registros_baja" integer, CONSTRAINT "PK_8c7e99758c774b801853b538647" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "persona_natural" ADD CONSTRAINT "FK_02e2cd4b8737ac553a32e529bed" FOREIGN KEY ("id_pais") REFERENCES "data_paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_estados_departamentos" ADD CONSTRAINT "FK_c6a0ecbf670cd0e76b9693a73f2" FOREIGN KEY ("id_pais") REFERENCES "data_paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_ciudades_municipios" ADD CONSTRAINT "FK_e66824311c1bf6d009896cbf279" FOREIGN KEY ("id_estado_departamento") REFERENCES "data_estados_departamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empresas" ADD CONSTRAINT "FK_2d25a87343439a177ffb3d279f5" FOREIGN KEY ("id_tipo_empresa") REFERENCES "categoria_empresa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_hechos_posteriores" ADD CONSTRAINT "FK_4d8eb450008ecec59005f89e906" FOREIGN KEY ("id_registros_baja") REFERENCES "registros_bajas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_hechos_posteriores" ADD CONSTRAINT "FK_fa598985026ce76e10693c111f8" FOREIGN KEY ("id_categoria_hechos_posteriores") REFERENCES "categoria_registro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_bajas" ADD CONSTRAINT "FK_7dd12ee6d33764502fb7974ba31" FOREIGN KEY ("id_registro_funcionario") REFERENCES "registros_funcionarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_bajas" ADD CONSTRAINT "FK_34616f87a19ec50ace6cd20fadd" FOREIGN KEY ("id_categoria_baja") REFERENCES "categoria_registro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" ADD CONSTRAINT "FK_48edc7105a5458696f177e992c9" FOREIGN KEY ("id_persona") REFERENCES "persona_natural"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" ADD CONSTRAINT "FK_0964456da02c1fa01e6ec3d63f8" FOREIGN KEY ("id_empresa") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" ADD CONSTRAINT "FK_8ebbeccdca3dad0e43ef2cdc248" FOREIGN KEY ("id_tipo_cargo") REFERENCES "catalogo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" ADD CONSTRAINT "FK_70a037599ff8a6f3aae6ebe2261" FOREIGN KEY ("id_estado_departamento") REFERENCES "data_estados_departamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" ADD CONSTRAINT "FK_7242ba403fae3600761af862cc5" FOREIGN KEY ("id_ciudad_municipio") REFERENCES "data_ciudades_municipios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes" ADD CONSTRAINT "FK_29f6bf2a991ceaf91f7e9be76f2" FOREIGN KEY ("id_empresa") REFERENCES "empresas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes" ADD CONSTRAINT "FK_a9a89072f0b53dcb258f55c91e8" FOREIGN KEY ("id_registros_baja") REFERENCES "registros_bajas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "solicitudes" DROP CONSTRAINT "FK_a9a89072f0b53dcb258f55c91e8"`);
        await queryRunner.query(`ALTER TABLE "solicitudes" DROP CONSTRAINT "FK_29f6bf2a991ceaf91f7e9be76f2"`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" DROP CONSTRAINT "FK_7242ba403fae3600761af862cc5"`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" DROP CONSTRAINT "FK_70a037599ff8a6f3aae6ebe2261"`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" DROP CONSTRAINT "FK_8ebbeccdca3dad0e43ef2cdc248"`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" DROP CONSTRAINT "FK_0964456da02c1fa01e6ec3d63f8"`);
        await queryRunner.query(`ALTER TABLE "registros_funcionarios" DROP CONSTRAINT "FK_48edc7105a5458696f177e992c9"`);
        await queryRunner.query(`ALTER TABLE "registros_bajas" DROP CONSTRAINT "FK_34616f87a19ec50ace6cd20fadd"`);
        await queryRunner.query(`ALTER TABLE "registros_bajas" DROP CONSTRAINT "FK_7dd12ee6d33764502fb7974ba31"`);
        await queryRunner.query(`ALTER TABLE "registros_hechos_posteriores" DROP CONSTRAINT "FK_fa598985026ce76e10693c111f8"`);
        await queryRunner.query(`ALTER TABLE "registros_hechos_posteriores" DROP CONSTRAINT "FK_4d8eb450008ecec59005f89e906"`);
        await queryRunner.query(`ALTER TABLE "empresas" DROP CONSTRAINT "FK_2d25a87343439a177ffb3d279f5"`);
        await queryRunner.query(`ALTER TABLE "data_ciudades_municipios" DROP CONSTRAINT "FK_e66824311c1bf6d009896cbf279"`);
        await queryRunner.query(`ALTER TABLE "data_estados_departamentos" DROP CONSTRAINT "FK_c6a0ecbf670cd0e76b9693a73f2"`);
        await queryRunner.query(`ALTER TABLE "persona_natural" DROP CONSTRAINT "FK_02e2cd4b8737ac553a32e529bed"`);
        await queryRunner.query(`DROP TABLE "solicitudes"`);
        await queryRunner.query(`DROP TABLE "registros_funcionarios"`);
        await queryRunner.query(`DROP TABLE "registros_bajas"`);
        await queryRunner.query(`DROP TABLE "registros_hechos_posteriores"`);
        await queryRunner.query(`DROP TABLE "empresas"`);
        await queryRunner.query(`DROP TABLE "categoria_empresa"`);
        await queryRunner.query(`DROP TABLE "catalogo"`);
        await queryRunner.query(`DROP TABLE "data_ciudades_municipios"`);
        await queryRunner.query(`DROP TABLE "data_estados_departamentos"`);
        await queryRunner.query(`DROP TABLE "categoria_registro"`);
        await queryRunner.query(`DROP TABLE "persona_natural"`);
        await queryRunner.query(`DROP TABLE "data_paises"`);
    }

}
